[package]
name = "crate-paths"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[features]
default = []
macro = ["dep:crate-paths-macro"]

[dependencies]
crate-paths-macro = { workspace = true, optional = true }
derive_more = { workspace = true, features = ["display"] }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
