[package]
name = "gpui-component-crate-paths"
version = "0.1.0"
categories.workspace = true
edition.workspace = true
license = "Unlicense"

[dependencies]
crate-paths.workspace = true

[lints]
workspace = true
